sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: uJRYnKm2H1lOwFAv/Wa4j2Y3PsMOQHd64QwxoQ3ol/H7ShroSQlpmgaBdZpk1YXHop3TZszVWWLU2968Wb/nbOD3ZLEP7XZT/M2rMrWEdldEKF3EYm5/Zr50/0S4GvY3pTA+Gc2O3949ZcgxTA1dDnVP+kTzUfdRNbVOlxTvrzG8rvKS6pOsJi++wnElScJt0ht6klTbap49yTXl0joXEnMYza2Iiysg+uMHfjVBIvK6kPWcvjYRiajPpeEYkAlwf4qE7teQlbs0UdiZQQaLHAFeLZtNtp7Hc5rkVg2+a7HvRw1ul7bi3Q1qsDVdMBhdZu5Zb9gwf6h66T5siQfR9w4ooRKQgkFm4vucBQEDUAx2LFhSbeqSF+kmVdS6J0iiejIwJlgvOYKAaByuXk2xdo3heSWDUpGnMJBj1ahAmwhad/k/2hkIFgy39GYbNegVcxXT9KtLdqZTNPvYTpSa6wHXRvIEcJ+oyy2XWITrCdYh8jqrynLqojb7dRQV2JF0kn0Xcq9SGO1qLdNNsMPg+eETs3XEsYT7s6p9PU8RNDDL07IUKc69HoFolPcuv3Cd6mzOlQvWU6BRspBnAtQeD0ggZ1kDAY6QonPI3P/hVddeVMFSe8qRataT0y8kZGkKdr0ALxStL7uWm2YV3/0UWQN/yz3Go1y4GZMdaiGR+L8=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: sMw9MZ95XzEJuTiAjOjixfAHorSrOWf44qJGZ1EhljqfcYrAuFp0XghsuX58GgZ1rQLqGSl0aikyJzkJNL9X90D7OHrpqWtzG/jiCnxHht3LcKRZQgD7Q0GAaDnQSDRpVN5WEAJf5wDr41D5hfGXNA9WHBzs9JMh/q0B5xo56batmY14jaPvJr8L4ERffAQ71AIxLJo4dbjAx+PWlmBpuZvTR490KFaJnCH0g2eHtp64aIlznFLtfo49bz5oKfLXpDifBPMZ58SNY/sXX5/UivypSJkTBTohTj+lvUNegU1AOuBOgKPXEKLdItNqmNxK0ql8S7wX2f05CnihbJF24EW6ffDOK325LuQrDF5pruaPBZC2JlDV5xnCxQ3jjJUrYVp1LxSC9VWzK7ikKKWPvTnqZ5b0urXMOjpp2K+aTGgDsZ7KSFcMNp5yBTgTdy3NARYft3XB109wdC7M5f7Ow1c8V3gcSgzSKX2f5GzNL4M3Sk0ZocAOPlB/YL8MYOED/3tjrIk0ezrH0gS9dyVux/iQsvl7tDuvr8CUKeEcqOY3ggdLwFqKWghdNCfTHBTQdOrsBj+dCX82t/cg7pSLMG/zpR0FPMtScnnt2GJ9mi2NagN14ijrC5Mp22aLVRUD1G7NQtt3lxgTj27q373Y5EPvXIQ2fnNfzU1U1stnr2Q=
